version: '2'
services:
  demo:
    container_name: demo-cmdline
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BIN_PACKAGE_PREFIX=spring-boot-demo-cmdline-Vanilla     
      - POST_EXEC_SLEEP_INTERVAL=30